### ISSUE TITLE
Generate openapi schema yaml from template to insert enums

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#192]
We have several places where enums are used in the [entity api schema](https://github.com/hubmapconsortium/entity-api/blob/test-release/entity-api-spec.yaml) for
 - [organs](https://github.com/hubmapconsortium/entity-api/blob/040a340c7a6d683b00fe8735c5c8aa4262d80b26/entity-api-spec.yaml#L467-L499)
 - [data/assay types](https://github.com/hubmapconsortium/entity-api/blob/040a340c7a6d683b00fe8735c5c8aa4262d80b26/entity-api-spec.yaml#L665-L708)
 - [specimen/sample type](https://github.com/hubmapconsortium/entity-api/blob/040a340c7a6d683b00fe8735c5c8aa4262d80b26/entity-api-spec.yaml#L403-L450)

We would like to pull these enum lists from their respective schema lists elsewhere so only one copy exists of each, these lists are here:
 - [organ](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/organ_types.yaml)
 - [specimen/sample type](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/assay_types.yaml)
 - [data/assay type](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/assay_types.yaml)

To this end we would like to create a Python script that takes, as input, the reference to a template that will further reference the sections that need to be replaced in the entity api schema.  For example, a file named entity-api-spec-TEMPLATE.yaml, which contains the full text of the entity api schema except for the sections that will be replaced which will look, for example,
```
      . . . .
         specimen_type:      
           type: string
           enum:
              X-replace-enum-list:
                enum-file-ref: https://raw.githubusercontent.com/hubmapconsortium/search-api/test-release/src/search-schema/data/definitions/enums/tissue_sample_types.yaml
      . . . .
```

The Python script will output the schema file with the enum replacements.

**Comment by shirey** [comment]
@DerekFurstPitt It looks like in the the generated yaml lists for enums need to be indented one more, both for enums that exist in a TEMPLATE file and for those that are being inserted via a `X-replace-enum-list:` directive, for example the generated file from entity-api-spec-TEMPLATE.yaml produces both:

```
        data_access_level:                                                                                                                     
          type: string 
          enum:                                                                                                                                
          - public                                                                                                                             
          - consortium
```
   and
```
        organ:                                                                                                                                 
          type: string                                                                                                                         
          enum:                                                                                                                                
          - AO                                                                                                                                 
          - BL                                                                                                                                 
          - BD                                                                                                                                 
          - BM                                                                                                                                 
          - BR                                                                                                                                 
          - LF                                                                                                                                 
          - RF    
```

but should be (with enum lists indented by two spaces):
```
        data_access_level:                                                                                                                     
          type: string 
          enum:                                                                                                                                
            - public                                                                                                                             
            - consortium
```
   and
```
        organ:                                                                                                                                 
          type: string                                                                                                                         
          enum:                                                                                                                                
            - AO                                                                                                                                 
            - BL                                                                                                                                 
            - BD                                                                                                                                 
            - BM                                                                                                                                 
            - BR                                                                                                                                 
            - LF                                                                                                                                 
            - RF    
```
