### ISSUE TITLE
Entity Superclassing

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#438]
Add a configuration item in the [provenance yaml file](https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml) to specify a superclass on an entity definition.  This is an optional parameter.  The superclass must be specified as an Entity name of another entity existing in the [provenance yaml file](https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml).  For now, the only effect will be that, at node creation time in Neo4j, if a superclass is specified then an additional node label with the superclass name.

The first use of this will be to add a new entity `Paper`, which will have a `Dataset` as it's superclass:

```
 ########################################### Paper ###########################################
  Paper:
    superclass: Dataset
    # Only allowed applications can create new Paper via POST
    before_entity_create_validator: validate_application_header_before_entity_create
    # Paper can be either derivation source or target
    derivation:
      source: false
      target: true
    properties:
      <<: *shared_properties
      <<: *shared_entity_properties
      <<: *doi_properties
      description:
        type: string
        description: "Free text description of the Paper"
  . . . 
```
