### ISSUE TITLE
Exclude fields from public responses

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#722]
For any "public" API response from either search-api or entity-api, i.e. GET requests that support public responses when there is either no token provided or a valid token without membership in `HuBMAP - Read` group:
Create a Entity level attribute in the provenance-schema.yaml file that lists fields to be excluded from these public responses.  Non-public responses (valid token with membership in `HuBMAP - Read`) should still contain these fields.
Example:
```
  Dataset:
    # Only allowed applications can create new Dataset via POST
    before_entity_create_validator: validate_application_header_before_entity_create
    # Dataset can be either derivation source or target
    derivation:
      source: true
      target: true
    excluded_properties_from_public_response:
      - lab_id
      - ingest_metadata.metadata.lab_id
    properties: &shared_dataset_properties
      <<: *shared_properties
      <<: *shared_entity_properties
      <<: *doi_properties
      antibodies:
        type: list

```

So for all entity-api GET calls matching the public response pattern, filter out these specified fields on response.  For search-api make sure these properties are filtered out before being added to the public indices.
